# Generated by Django 3.2.5 on 2021-07-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=500)),
                ('desc', models.CharField(default='', max_length=5000)),
                ('email', models.CharField(default='', max_length=500)),
                ('phone', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
